export function taskListData() {
    var list =
        [
            {
                productName: '云数据库MySQL',
                testType: '产品自测',
                testDimension: '集团级',
                time: '3小时',
                people: '8名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '中移舆情',
                testType: '产品自测',
                testDimension: '公司级',
                time: '1.5小时',
                people: '11名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '测评中',
            },
            {
                productName: '云信',
                testType: '产品自测',
                testDimension: '部门级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '云数据库MySQL',
                testType: '产品自测',
                testDimension: '集团级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '云信',
                testType: '产品自测',
                testDimension: '部门级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            }, {
                productName: '云信',
                testType: '产品自测',
                testDimension: '部门级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '测评中',
            },
            {
                productName: '云数据库MySQL',
                testType: '产品自测',
                testDimension: '集团级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '中移舆情',
                testType: '产品自测',
                testDimension: '公司级',
                time: '1.5小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '云信',
                testType: '产品自测',
                testDimension: '部门级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '测评中',
            },
            {
                productName: '云数据库MySQL',
                testType: '产品自测',
                testDimension: '集团级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '云信',
                testType: '产品自测',
                testDimension: '部门级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            }, {
                productName: '云信',
                testType: '产品自测',
                testDimension: '部门级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '云数据库MySQL',
                testType: '产品自测',
                testDimension: '集团级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '已结束',
            },
            {
                productName: '云数据库MySQL',
                testType: '产品自测',
                testDimension: '集团级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '中移舆情',
                testType: '产品自测',
                testDimension: '公司级',
                time: '1.5小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '云信',
                testType: '产品自测',
                testDimension: '部门级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '测评中',
            },
            {
                productName: '云数据库MySQL',
                testType: '产品自测',
                testDimension: '集团级',
                time: '3小时',
                people: '8名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '中移舆情',
                testType: '产品自测',
                testDimension: '公司级',
                time: '1.5小时',
                people: '11名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '已结束',
            },
            {
                productName: '云信',
                testType: '产品自测',
                testDimension: '部门级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '云数据库MySQL',
                testType: '产品自测',
                testDimension: '集团级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '测评中',
            },
            {
                productName: '云信',
                testType: '产品自测',
                testDimension: '部门级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            }, {
                productName: '云信',
                testType: '产品自测',
                testDimension: '部门级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '云数据库MySQL',
                testType: '产品自测',
                testDimension: '集团级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '中移舆情',
                testType: '产品自测',
                testDimension: '公司级',
                time: '1.5小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '已结束',
            },
            {
                productName: '云信',
                testType: '产品自测',
                testDimension: '部门级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '云数据库MySQL',
                testType: '产品自测',
                testDimension: '集团级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '云信',
                testType: '产品自测',
                testDimension: '部门级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            }, {
                productName: '云信',
                testType: '产品自测',
                testDimension: '部门级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '测评中',
            },
            {
                productName: '云数据库MySQL',
                testType: '产品自测',
                testDimension: '集团级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '云数据库MySQL',
                testType: '产品自测',
                testDimension: '集团级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '中移舆情',
                testType: '产品自测',
                testDimension: '公司级',
                time: '1.5小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '云信',
                testType: '产品自测',
                testDimension: '部门级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '测评中',
            },
            {
                productName: '云数据库MySQL',
                testType: '产品自测',
                testDimension: '集团级',
                time: '3小时',
                people: '8名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '中移舆情',
                testType: '产品自测',
                testDimension: '公司级',
                time: '1.5小时',
                people: '11名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '云信',
                testType: '产品自测',
                testDimension: '部门级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '云数据库MySQL',
                testType: '产品自测',
                testDimension: '集团级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '云信',
                testType: '产品自测',
                testDimension: '部门级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '已结束',
            }, {
                productName: '云信',
                testType: '产品自测',
                testDimension: '部门级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '云数据库MySQL',
                testType: '产品自测',
                testDimension: '集团级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '中移舆情',
                testType: '产品自测',
                testDimension: '公司级',
                time: '1.5小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '测评中',
            },
            {
                productName: '云信',
                testType: '产品自测',
                testDimension: '部门级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '云数据库MySQL',
                testType: '产品自测',
                testDimension: '集团级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '云信',
                testType: '产品自测',
                testDimension: '部门级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '测评中',
            }, {
                productName: '云信',
                testType: '产品自测',
                testDimension: '部门级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '云数据库MySQL',
                testType: '产品自测',
                testDimension: '集团级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '云数据库MySQL',
                testType: '产品自测',
                testDimension: '集团级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '已结束',
            },
            {
                productName: '中移舆情',
                testType: '产品自测',
                testDimension: '公司级',
                time: '1.5小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '招募中',
            },
            {
                productName: '云信',
                testType: '产品自测',
                testDimension: '部门级',
                time: '3小时',
                people: '9名',
                collectDate: '2016/12/19-2017/01/19',
                testDate: '2016/12/19-2017/01/19',
                status: '测评中',
            },
        ]
    return list;
}