export function userData() {
  var user =
    [
      {
        department: 'PaaS部',
        name: '卜雅',
        phone: '15393867877',
        completion: '1/2',
      },
      {
        department: 'LaaS部',
        name: '黄娟璐',
        phone: '19940498277',
        completion: '2/2',
      },
      {
        department: 'PaaS部',
        name: '商江',
        phone: '18491687150',
        completion: '4/4',
      },
      {
        department: 'LaaS部',
        name: '钟佳',
        phone: '19706020153',
        completion: '4/5',
      },
      {
        department: 'LaaS部',
        name: '姜可茜',
        phone: '13184694223',
        completion: '1/3',
      },
      {
        department: 'PaaS部',
        name: '卜雅',
        phone: '15393867877',
        completion: '1/2',
      },
      {
        department: 'LaaS部',
        name: '黄娟璐',
        phone: '19940498277',
        completion: '2/2',
      },
      {
        department: 'LaaS部',
        name: '钟佳',
        phone: '19706020153',
        completion: '4/5',
      },
      {
        department: 'PaaS部',
        name: '商江',
        phone: '18491687150',
        completion: '4/4',
      },
      {
        department: 'LaaS部',
        name: '姜可茜',
        phone: '13184694223',
        completion: '1/3',
      },
      {
        department: 'PaaS部',
        name: '卜雅',
        phone: '15393867877',
        completion: '1/2',
      },
      {
        department: 'LaaS部',
        name: '黄娟璐',
        phone: '19940498277',
        completion: '2/2',
      },
      {
        department: 'PaaS部',
        name: '商江',
        phone: '18491687150',
        completion: '4/4',
      },
      {
        department: 'LaaS部',
        name: '钟佳',
        phone: '19706020153',
        completion: '4/5',
      },
      {
        department: 'LaaS部',
        name: '姜可茜',
        phone: '13184694223',
        completion: '1/3',
      },
      {
        department: 'PaaS部',
        name: '卜雅',
        phone: '15393867877',
        completion: '1/2',
      },
      {
        department: 'LaaS部',
        name: '黄娟璐',
        phone: '19940498277',
        completion: '2/2',
      },
      {
        department: 'LaaS部',
        name: '钟佳',
        phone: '19706020153',
        completion: '4/5',
      },
      {
        department: 'PaaS部',
        name: '商江',
        phone: '18491687150',
        completion: '4/4',
      },
      {
        department: 'LaaS部',
        name: '姜可茜',
        phone: '13184694223',
        completion: '1/3',
      },
      {
        department: 'PaaS部',
        name: '卜雅',
        phone: '15393867877',
        completion: '1/2',
      },
      {
        department: 'LaaS部',
        name: '黄娟璐',
        phone: '19940498277',
        completion: '2/2',
      },
      {
        department: 'PaaS部',
        name: '商江',
        phone: '18491687150',
        completion: '4/4',
      },
      {
        department: 'LaaS部',
        name: '钟佳',
        phone: '19706020153',
        completion: '4/5',
      },
      {
        department: 'LaaS部',
        name: '姜可茜',
        phone: '13184694223',
        completion: '1/3',
      },
      {
        department: 'PaaS部',
        name: '卜雅',
        phone: '15393867877',
        completion: '1/2',
      },
      {
        department: 'LaaS部',
        name: '黄娟璐',
        phone: '19940498277',
        completion: '2/2',
      },
      {
        department: 'LaaS部',
        name: '钟佳',
        phone: '19706020153',
        completion: '4/5',
      },
      {
        department: 'PaaS部',
        name: '商江',
        phone: '18491687150',
        completion: '4/4',
      },
      {
        department: 'LaaS部',
        name: '姜可茜',
        phone: '13184694223',
        completion: '1/3',
      },
      {
        department: 'PaaS部',
        name: '卜雅',
        phone: '15393867877',
        completion: '1/2',
      },
      {
        department: 'LaaS部',
        name: '黄娟璐',
        phone: '19940498277',
        completion: '2/2',
      },
      {
        department: 'PaaS部',
        name: '商江',
        phone: '18491687150',
        completion: '4/4',
      },
      {
        department: 'LaaS部',
        name: '钟佳',
        phone: '19706020153',
        completion: '4/5',
      },
      {
        department: 'LaaS部',
        name: '姜可茜',
        phone: '13184694223',
        completion: '1/3',
      },
      {
        department: 'PaaS部',
        name: '卜雅',
        phone: '15393867877',
        completion: '1/2',
      },
      {
        department: 'LaaS部',
        name: '黄娟璐',
        phone: '19940498277',
        completion: '2/2',
      },
      {
        department: 'LaaS部',
        name: '钟佳',
        phone: '19706020153',
        completion: '4/5',
      },
      {
        department: 'PaaS部',
        name: '商江',
        phone: '18491687150',
        completion: '4/4',
      },
      {
        department: 'LaaS部',
        name: '姜可茜',
        phone: '13184694223',
        completion: '1/3',
      },
      {
        department: 'PaaS部',
        name: '卜雅',
        phone: '15393867877',
        completion: '1/2',
      },
      {
        department: 'LaaS部',
        name: '黄娟璐',
        phone: '19940498277',
        completion: '2/2',
      },
      {
        department: 'PaaS部',
        name: '商江',
        phone: '18491687150',
        completion: '4/4',
      },
      {
        department: 'LaaS部',
        name: '钟佳',
        phone: '19706020153',
        completion: '4/5',
      },
      {
        department: 'LaaS部',
        name: '姜可茜',
        phone: '13184694223',
        completion: '1/3',
      },
      {
        department: 'PaaS部',
        name: '卜雅',
        phone: '15393867877',
        completion: '1/2',
      },
      {
        department: 'LaaS部',
        name: '黄娟璐',
        phone: '19940498277',
        completion: '2/2',
      },
      {
        department: 'LaaS部',
        name: '钟佳',
        phone: '19706020153',
        completion: '4/5',
      },
      {
        department: 'PaaS部',
        name: '商江',
        phone: '18491687150',
        completion: '4/4',
      },
      {
        department: 'LaaS部',
        name: '姜可茜',
        phone: '13184694223',
        completion: '1/3',
      },
      {
        department: 'PaaS部',
        name: '卜雅',
        phone: '15393867877',
        completion: '1/2',
      },
      {
        department: 'LaaS部',
        name: '黄娟璐',
        phone: '19940498277',
        completion: '2/2',
      },
      {
        department: 'PaaS部',
        name: '商江',
        phone: '18491687150',
        completion: '4/4',
      },
      {
        department: 'LaaS部',
        name: '钟佳',
        phone: '19706020153',
        completion: '4/5',
      },
      {
        department: 'LaaS部',
        name: '姜可茜',
        phone: '13184694223',
        completion: '1/3',
      },
      {
        department: 'PaaS部',
        name: '卜雅',
        phone: '15393867877',
        completion: '1/2',
      },
      {
        department: 'LaaS部',
        name: '黄娟璐',
        phone: '19940498277',
        completion: '2/2',
      },
      {
        department: 'LaaS部',
        name: '钟佳',
        phone: '19706020153',
        completion: '4/5',
      },
      {
        department: 'PaaS部',
        name: '商江',
        phone: '18491687150',
        completion: '4/4',
      },
      {
        department: 'LaaS部',
        name: '姜可茜',
        phone: '13184694223',
        completion: '1/3',
      },
    ];
  return user;
}